### ISSUE TITLE
파일전송 이어받기 2

### ISSUE THREAD

**Issue by solee5155** [niceguy1575/Spp#10]
파일 전송시 끊겼을떄 
1. 파일을 이어받기 해야할까?
2. 파일을 덮어써야 하는 걸까?

제법 큰file을 전송 할 경우에 덮어쓰는 것은 무리가 있다고 보고 이어받기로 기능 추가를 해야한다고 생각하는데 ?!!

**Comment by Seong-Mook-Jeong** [comment]
덮어쓰는 방법은 그냥 다시 받는것과 같아보이는데 나도 이어 받는게 맞는것으로 생각됨

**Comment by 201213006** [comment]
이어받기로 기능추가 하는게 이번 과제에 더 적합한거 같다고 생각해
