### ISSUE TITLE
통계서버 구축관련

### ISSUE THREAD

**Issue by niceguy1575** [niceguy1575/Spp#12]
JAVA와 R을 Connect시켜서 더욱 쉽게 분석할 수 있는 방법을 활용했으면 합니다.

검색결과 R에서는 Rserve 패키지를, JAVA에서는 R engine JAR 을 빌드하는 방식으로 연결합니다.

**Comment by 201213006** [comment]
그럼 그렇게 연결해서 데이터가 들어왔을 때 사용자가 그 데이터에 대한 통계적 분석을 원하면 자동적으로 R에서 실행될 수 있도록 기능 추가하도록 하면 좋을 듯해

**Comment by solee5155** [comment]
통계분석은 JAVA보다 R이 보편적으로 많이 사용되고 통계분석에 좀 더 적합한것 같아 좋은 방법인것같습니다~

**Comment by Seong-Mook-Jeong** [comment]
통계분석에 대해 지식이 부족한 사람들은 R에 대해 생소 할텐데 이러한 것도 생각하보면 좋지 않을까?
