### ISSUE TITLE
[Server] V0.5 Issue정리

### ISSUE THREAD

**Issue by niceguy1575** [niceguy1575/Spp#13]
A. 서버에서의 통계분석 결과를 클라이언트에게 어떻게 보내줄지에 대한 생각

- 서버에서 결과를 얻은 후 파일(플랏.jpg, sumarry.txt)로 저장 -> 프로토콜을 통해 전송
- 서버에서의 결과를 클라이언트에게 센드 후 클라이언트에서 출력.

2번 방법은 서버가 보내야 할 데이터 양이 많다면 어려울것으로 생각됩니다.
따라서 1번 방법이 쉬울것 같습니다. 이렇게 구현하기 위해서는 서버에도 파일을 전송할 수 있는 메소드를 달아줘야합니다.

B. ClientUI Update

V0.4의 영향으로 Client UI가 특정 기능을 수행하기 위한 UI로 바뀌어 있는 상황입니다.
V0.5에 맞게 UI 업데이트가 필요하다고 생각합니다.
(IP/PORT, 분석파일경로, 결과 저장경로, 용량 판단기능, MAIN문이 최소화 되었으면 합니다.)

C. JAVA to R

Client로부터 얻은 파일을 분석에 용이한 자료구조로 알맞게 분해하고 이를 R에 넘겨서 결과를 얻어낼 수 있는 메소드를 구현해야합니다.

D. 통계 기능에 대하여

현재까지 생각해본 통계기능
1. Regression (결과 검토)
2. 자료의 Summary
3. Data Visualization (회귀분석 혹은 BOXPLOT )
4. 추후 추가.

**Comment by niceguy1575** [comment]
C에 해당하는 자료구조에 대하여...
들어오는 변수를 하나의 더블형 배열로 둔다.
변수의 종류는 다양하지만 Discrete이던지 Continuous던지 numeric하기때문에 double형 변수면 될 듯 하다.
하지만 더블형 배열을 동적으로 할당하기위해서는 데이터의 column count를 확인해야하고
한줄씩 읽을때 String을 분리하여 col num을 확인한다.

**Comment by niceguy1575** [comment]
A의 결과 회신에 대하여...
서버에서 자료를 다시 보내줄때를 위해서 서버-클라이언트 구현시 서버가 파일을 받고 나서  종료되지 않도록 프로토콜을 다시 설계해야합니다.

**Comment by niceguy1575** [comment]
A에서 Client가 보내는 Input에 대하여...
CSV파일, TXT파일이 들어오는것을 가정한다.
자료의 형식은 변수명(첫행), 자료 (나머지 행) 의 matrix형태로 구성된다.
missing value에 대해서는 0으로 처리한다. (line단위의 파일을 읽을 경우 한줄을 배열로 받게 되는데 만약 끝값이 missing value일 경우에는 length가 1 줄어들고 그렇지 않은 경우는 length가 그대로이다.)

다시 확인해보니 R connection 후 read.csv or read.table 함수를 사용하니 이상없이 잘 됩니다....

**Comment by niceguy1575** [comment]
C의 문제.
R의 자료를 메모리에 로드한다면 변수를 동적으로 할당할 필요가 없어짐을 확인했습니다.

**Comment by niceguy1575** [comment]
D의 1, 2 구현 완료

**Comment by niceguy1575** [comment]
A 진행순서
1. Server는 받은 파일을 열어야한다.
2. Server는 작업을한다.
3. 결과를 save한다. (폼에 맞춰서 txt and jpg)
4. 그 파일을 다시 클라이언트에게 보내준다.

**Comment by niceguy1575** [comment]
1 ~ 3 해결

**Comment by niceguy1575** [comment]
서버가 2개인 경우에는 입력작업이 동시에 진행됨.
따라서 이 경우를 위해서 Thread를 10초정도 쉬게한다.

**Comment by Seong-Mook-Jeong** [comment]
파일을 그림이나 텍스트 형식으로 저장을 하고 나서 클라이언트에게 보내주는방법이 좋을듯 하네요
자바환경에서 R에서 나온 결과를 보여주는일은 힘들테니 결과파일만 따로 해서 보내주는게 좋을거 같다는 생각
