### ISSUE TITLE
client에서 파일이 연속하여 보내지지 않습니다.

### ISSUE THREAD

**Issue by niceguy1575** [niceguy1575/Spp#14]
확인하여 조치바랍니다.

**Comment by Seong-Mook-Jeong** [comment]
확인해보겠습니다

**Comment by niceguy1575** [comment]
또한 전송 속도에 대한 고민도 필요할것 같습니다. 수정할지 아니면 필요없는 부분이니 제거할지에 대한 고민은 할만하다고 생각합니다~

**Comment by 201213035a** [comment]
Sever에서 send메소드로 보내주지 않은 값(속도)을 UI에서 receive메소드로 받아서 사용하려고 해서 생긴 오류였습니다. 트렐로에서 마감된 이슈입니다. 종료시기겠습니다.
