### ISSUE TITLE
V0.5 BUG

### ISSUE THREAD

**Issue by 201213006** [niceguy1575/Spp#15]
data 자료 전송하기 위해 TCP서버와 UDP서버를 둘다 켜고 실행하게 되면 두 서버가 R과 연결시키려 하였는데 TCP서버와 UDP서버 중 먼저 켠 서버만 실행되고 그 외 서버가 켜지지 않아 실행이 되지 않는 버그가 발생하였습니다.

**Comment by niceguy1575** [comment]
해결하였음을 확인했습니다.
