### ISSUE TITLE
check UDP & TCP integrity 

### ISSUE THREAD

**Issue by niceguy1575** [niceguy1575/Spp#2]
무결성 검사 구현이 필요합니다.

**Comment by niceguy1575** [comment]
TCP의 경우 20170410 현재 원격 컴퓨터간의 전송은 테스트 하지 않았습니다.
테스트를 하십시오.

**Comment by 201213035a** [comment]
무결성 검사에 자바에 구현된 CRC32, checksum 사용해서 구현하려고 합니다.

**Comment by 201213035a** [comment]
![kakaotalk_20170413_222446049](https://cloud.githubusercontent.com/assets/26472144/25006673/d62be8e6-2098-11e7-85c4-ca946361cc83.png)

무결성 검사 구현 완료한것 같습니다.
내일 같이 코드 확인하면서 누락된 부분이나 부족한 부분 보완후에 git에 올리는게 좋겠습니다.
