### ISSUE TITLE
사용자 시점 편의성 도모

### ISSUE THREAD

**Issue by 201213035a** [niceguy1575/Spp#3]
![image](https://cloud.githubusercontent.com/assets/26472144/24909786/58fa9d02-1f00-11e7-96eb-bd9da3d90902.png)

서버에 있는 파일을 클라이언트에서 받아올때 
위에 주석문같이 Scanner를 사용해야 할까 
아니면 사용자가 직접 객체생성에 집어넣는게 좋을까?

**Comment by niceguy1575** [comment]
개발의 편의성을 도모하기 위해서 일단은 생성자를 활용하고, 릴리즈 버전에서 scanner로 전환하는게 좋을것같다는 생각

**Comment by solee5155** [comment]
niceguy말에 동의함. 굳이 계속 test해야하는 과정에서 scanner를 사용하는 것은 비효율적인것 같다는 생각
