### ISSUE TITLE
file 전송속도 측정 문제(전체 전송속도를 해야할까 file 전송속도만 봐야할까?)

### ISSUE THREAD

**Issue by solee5155** [niceguy1575/Spp#5]
client가 연결되고나서부터 file수신이 완료될때 까지의 시간 측정

vs

순수하게 file의 전송속도만 측정하는것이 맞을까?

**Comment by 201213035a** [comment]
나는 전자가 맞다고봄 전송완료라고 함은 내가 파일을 다 받았어야 전송완료이니까
전송완료된 파일의 크기/총 걸린시간 이게 전송시간이 아닐까?

**Comment by niceguy1575** [comment]
전자에서 클라이언트 연결보다는 클라이언트 파일 전송 부터 가 더 정확한 표현이지 않을까?

**Comment by Seong-Mook-Jeong** [comment]
파일이 전송 되는 속도를 물어보는거니까 client가 연결 되소 나서 부터면  파일을 보내기 전까지 계속해서 시간이 말이지 않아?? 순수하게 파일만 전송되는 시간을 측정해주는게 파일 전송 속도라고 할수 있을거 같아!

**Comment by 201213006** [comment]
다 비슷비슷한 말이데 종원이 말처럼 하면 순수한 file 전송속도 측정 가능할 거 같아
