### ISSUE TITLE
디렉토리 전송문제

### ISSUE THREAD

**Issue by 201213006** [niceguy1575/Spp#6]
디렉토리를 전송하는 것이 
1.디렉토리를 통째로 한 번에 다 전송하는 건지? 
2.하나하나 전송하는 건지? 
3.파일 압축하여 그것을 옮기는 것인지?
우선 구현은 하나하나 전송하는 것으로 구현완료!

**Comment by 201213035a** [comment]
하나하나 보내면 무결성체크 4번진행되니까 1개가 이상이 있더라도 3개는 전송이 되니까 하나하나 보내느게 더 좋은것 같아
압축파일을 전송하게 되면 무결성을 한번만 진행하는데 진행할때 오류가나면 모든 파일을 못받게 되는 거니까

**Comment by solee5155** [comment]
필요한 디렉토리를 Client가 보내주기 때문에 Client 필요한 것들만 모아서 한번에 전송하는 것으로 서로 이야기 하면 될거같으니 하나로 모아서 하나만 전송하는 것도 나쁘지 않아보임~!
