### ISSUE TITLE
파일전송 이어받기

### ISSUE THREAD

**Issue by 201213035a** [niceguy1575/Spp#9]
윈도우에서도 같은 이름의 파일을 같은 폴더에 복사붙여넣기 할때 메시지 창이 뜨는 것처럼 
우리도 파일의 제목을 이용해서
1. 사용자가 판단할 수 있게 하는게 
2. 단순하게 같은 파일명이면 같은 파일로 간주해서 진행

**Comment by Seong-Mook-Jeong** [comment]
사용자가 판단후에 하는게 좋으듯 파일명만 같고 내용이 달라지게 되면 정보를 손실할 수 있는 경우가 생길수 있으니 확인후 하거나 하는걸로하는게 좋을것으로 생각됨
